// Generated by CoffeeScript 2.5.0
(function() {
  var getSearchString, tb;

  getSearchString = function() {
    var i, item, len, obj, ref, str, tmp_arr;
    str = location.search;
    str = str.substring(1, str.length);
    obj = {};
    ref = str.split("&");
    for (i = 0, len = ref.length; i < len; i++) {
      item = ref[i];
      tmp_arr = item.split("=");
      obj[decodeURIComponent(tmp_arr[0])] = decodeURIComponent(tmp_arr[1]);
    }
    return obj;
  };

  tb = getSearchString();

  if (tb['a'] && tb['b']) {
    window.location.href = tb['b'];
  }

}).call(this);
